on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  capture:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: snok/install-poetry@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'poetry'
    - name: install python deps
      run: |
        poetry install  --no-interaction --no-root
        sudo $(poetry env info --path)/bin/playwright install-deps webkit
        $(poetry env info --path)/bin/playwright install webkit
    - run: poetry run python capture.py
    - uses: stefanzweifel/git-auto-commit-action@v5
