on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snok/install-poetry@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'poetry'
    - run: |
        poetry install --no-interaction --no-root
        sudo poetry run playwright install-deps
        poetry run playwright install webkit
        poetry run python capture.py
    - uses: stefanzweifel/git-auto-commit-action@v5
