on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snok/install-poetry@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'poetry'
    - run: |
        poetry install --no-interaction --no-root
        sudo apt-get install libwoff1\                   
           libvpx9\                                     
           libevent-2.1-7t64\                           
           libopus0\                                    
           libgstreamer-plugins-base1.0-0\              
           libgstreamer-gl1.0-0\                        
           libgstreamer-plugins-bad1.0-0\               
           libflite1\                                   
           libavif16\                                   
           libharfbuzz-icu0\                            
           libsecret-1-0\                               
           libhyphen0\                                  
           libmanette-0.2-0\                            
           libgles2\                                    
           gstreamer1.0-libav
        poetry run playwright install webkit
        poetry run python capture.py
    - uses: stefanzweifel/git-auto-commit-action@v5
